export const cardData = [
  {
    id: 1,
    title: "Alpha Trading Group",
    //add new
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmPageURL: "https://alphafunded.com/ref/1491/", //add new
    firmType: "premium", //add new
    profitSplit: 80,
    account: 1000000.0,
    code: "TPO",
    logo: "/firms/alpha-trading.png",
    isActive: true, // add new
    rating: "A+",
    allRatings: 36,
    country: "USA",
    flag: "/flags/usaflag.jpeg",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT4", "Match Trader", "Trade Locker"],
    maxAllocation: 1000000,
  },
  {
    id: 2,
    title: "Auqa Funded",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "premium",
    profitSplit: 90,
    account: 150000.0,
    code: "TPO",
    logo: "/firms/Auqa-funded.png",
    isActive: true,
    rating: "A+",
    allRatings: 25,
    country: "UAE",
    flag: "/flags/uaeflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "cTrader", "Trade Locker", "Project-X"],
    maxAllocation: 200000,
  },
  {
    id: 3,
    title: "Blue Guardian",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "premium",
    profitSplit: 75,
    account: 200000.0,
    code: "TPO",
    logo: "/firms/Blue-guardian.png",
    isActive: true,
    rating: "A+",
    allRatings: 30,
    country: "UAE",
    flag: "/flags/uaeflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "cTrader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 4,
    title: "Blueberry Funded",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "premium",
    profitSplit: 80,
    account: 250000.0,
    code: "TPO",
    logo: "/firms/Blueberry-funded.png",
    isActive: true,
    rating: "A+",
    allRatings: 20,
    country: "USA",
    flag: "/flags/usaflag.jpeg",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT4", "Match Trader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 5,
    title: "QUANT REKEL",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "premium",
    profitSplit: 70,
    account: 200000.0,
    code: "TPO",
    logo: "/firms/Quant-tekel.png",
    isActive: true,
    rating: "A+",
    allRatings: 23,
    country: "SA",
    flag: "/flags/saflag.jpg",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "DX Trade"],
    maxAllocation: 400000,
  },
  {
    id: 6,
    title: "Real Funded",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "premium",
    profitSplit: 80,
    account: 100000.0,
    code: "TPO",
    logo: "/firms/Real-funded.jpg",
    isActive: true,
    rating: "A+",
    allRatings: 14,
    country: "UK",
    flag: "/flags/ukflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT4", "Match Trader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 7,
    title: "Soar Fundeding",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "premium",
    profitSplit: 80,
    account: 100000.0,
    code: "TPO",
    logo: "/firms/Soar-funding.jpg",
    isActive: true,
    rating: "A",
    allRatings: 25,
    country: "UK",
    flag: "/flags/ukflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 200000,
  },
  {
    id: 11,
    title: "Alpha Trading Group",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "partner",
    profitSplit: 80,
    account: 1000000.0,
    code: "TPO",
    logo: "/alpha-trading.png",
    isActive: true,
    rating: "B",
    allRatings: 36,
    country: "USA",
    flag: "/flags/usaflag.jpeg",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT4", "DX Trade", "Trade Locker"],
    maxAllocation: 1000000,
  },
  {
    id: 12,
    title: "Auqa Funded",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "partner",
    profitSplit: 90,
    account: 150000.0,
    code: "TPO",
    logo: "/firms/Auqa-funded.png",
    isActive: true,
    rating: "A",
    allRatings: 25,
    country: "UAE",
    flag: "/flags/uaeflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "cTrader", "Trade Locker", "Project-X"],
    maxAllocation: 200000,
  },
  {
    id: 13,
    title: "Blue Guardian",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "partner",
    profitSplit: 75,
    account: 200000.0,
    code: "TPO",
    logo: "/firms/Blue-guardian.png",
    isActive: true,
    rating: "A",
    allRatings: 30,
    country: "UAE",
    flag: "/flags/uaeflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "cTrader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 14,
    title: "Blueberry Funded",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "partner",
    profitSplit: 80,
    account: 250000.0,
    code: "TPO",
    logo: "/firms/Blueberry-funded.png",
    isActive: true,
    rating: "C",
    allRatings: 20,
    country: "USA",
    flag: "/flags/usaflag.jpeg",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 15,
    title: "QUANT REKEL",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "partner",
    profitSplit: 70,
    account: 200000.0,
    code: "TPO",
    logo: "/firms/Quant-tekel.png",
    isActive: true,
    rating: "D",
    allRatings: 23,
    country: "SA",
    flag: "/flags/saflag.jpg",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 16,
    title: "Real Funded",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "partner",
    profitSplit: 80,
    account: 100000.0,
    code: "TPO",
    logo: "/firms/Real-funded.jpg",
    isActive: true,
    rating: "B",
    allRatings: 14,
    country: "UK",
    flag: "/flags/ukflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 17,
    title: "Soar Fundeding",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "partner",
    profitSplit: 80,
    account: 100000.0,
    code: "TPO",
    logo: "/firms/Soar-funding.jpg",
    isActive: true,
    rating: "A",
    allRatings: 25,
    country: "UK",
    flag: "/flags/ukflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 200000,
  },
  {
    id: 21,
    title: "Alpha Trading Group",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "trusted",
    profitSplit: 80,
    account: 1000000.0,
    code: "TPO",
    logo: "/alpha-trading.png",
    isActive: true,
    rating: "C",
    allRatings: 36,
    country: "USA",
    flag: "/flags/usaflag.jpeg",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 1000000,
  },
  {
    id: 22,
    title: "Auqa Funded",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "trusted",
    profitSplit: 90,
    account: 150000.0,
    code: "TPO",
    logo: "/firms/Auqa-funded.png",
    isActive: true,
    rating: "D",
    allRatings: 25,
    country: "UAE",
    flag: "/flags/uaeflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "cTrader", "Trade Locker", "Project-X"],
    maxAllocation: 200000,
  },
  {
    id: 23,
    title: "Blue Guardian",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "trusted",
    profitSplit: 75,
    account: 200000.0,
    code: "TPO",
    logo: "/firms/Blue-guardian.png",
    isActive: true,
    rating: "A",
    allRatings: 30,
    country: "UAE",
    flag: "/flags/uaeflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "cTrader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 24,
    title: "Blueberry Funded",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "trusted",
    profitSplit: 80,
    account: 250000.0,
    code: "TPO",
    logo: "/firms/Blueberry-funded.png",
    isActive: true,
    rating: "C",
    allRatings: 20,
    country: "USA",
    flag: "/flags/usaflag.jpeg",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 25,
    title: "QUANT REKEL",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "trusted",
    profitSplit: 70,
    account: 200000.0,
    code: "TPO",
    logo: "/firms/Quant-tekel.png",
    isActive: true,
    rating: "B",
    allRatings: 23,
    country: "SA",
    flag: "/flags/saflag.jpg",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 26,
    title: "Real Funded",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "trusted",
    profitSplit: 80,
    account: 100000.0,
    code: "TPO",
    logo: "/firms/Real-funded.jpg",
    isActive: true,
    rating: "B",
    allRatings: 14,
    country: "UK",
    flag: "/flags/ukflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 400000,
  },
  {
    id: 27,
    title: "Soar Fundeding",
    description:
      "is a proprietary trading firm that started in 2022 and offers a variety of funding challenges for traders: Simulated evaluation challenges (one-step, two-step) Instant funding accounts High-tier 'Funded King' challenge up to $1M accounts Profit share up to 90%, with daily to bi-weekly payouts via Rise Pay They integrate their own TradeLocker platform alongside MT5 and MatchTrader for trading.",
    firmURL: "#",
    firmType: "premium",
    profitSplit: 80,
    account: 100000.0,
    code: "TPO",
    logo: "/firms/Soar-funding.jpg",
    isActive: true,
    rating: "A+",
    allRatings: 25,
    country: "UK",
    flag: "/flags/ukflag.png",
    assets: ["forex", "crypto", "indices"],
    platforms: ["MT5", "Match Trader", "Trade Locker"],
    maxAllocation: 200000,
  },
];
